name: dart_twitter_api
description: A dart wrapper for using the Twitter API with well documented interfaces for every endpoint.
version: 0.4.0-nullsafety.0
homepage: https://github.com/robertodoering/twitter_api
repository: https://github.com/robertodoering/twitter_api
issue_tracker: https://github.com/robertodoering/twitter_api/issues

environment:
  sdk: '>=2.12.0-133.7.beta <3.0.0'

dependencies:
 http: ^0.13.0-nullsafety.0
 intl: ^0.17.0-nullsafety.2
 json_annotation: ^4.0.0-nullsafety.0
 oauth1: ^2.0.0-nullsafety.0

dev_dependencies:
  build_runner: ^1.11.1
  json_serializable: ^4.0.0-nullsafety.0
  mockito: ^5.0.0-nullsafety.5
  pedantic: ^1.9.2
  test: ^1.15.7
