name: twitter_api
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
 oauth1: ^1.0.4
 json_annotation: ^3.0.1
 intl: ^0.16.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  build_runner: ^1.7.3
  json_serializable: ^3.2.5
